# Generated by Django 5.0.2 on 2024-02-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="freelancer",
            name="phone",
            field=models.PositiveIntegerField(),
        ),
    ]
