# Generated by Django 5.0.2 on 2024-02-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_freelancer_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="company_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="discription",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="freelancer",
            name="discription",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="freelancer",
            name="phone",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="freelancer",
            name="portofolio",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="freelancer",
            name="skills",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
